/**
 * Standardized Application Error Codes for Mobile (Flutter), Web (Next.js), and API Clients.
 * These error codes enable programmatic i18n localization, UI alerts, and automated recovery actions.
 */
export enum AppErrorCode {
  // Common / General Errors
  SUCCESS = 'SUCCESS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Authentication & Authorization Errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  API_KEY_MISSING = 'API_KEY_MISSING',
  API_KEY_INVALID = 'API_KEY_INVALID',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Database / Prisma Errors
  DB_UNIQUE_CONSTRAINT_VIOLATION = 'DB_UNIQUE_CONSTRAINT_VIOLATION',
  DB_RECORD_NOT_FOUND = 'DB_RECORD_NOT_FOUND',
  DB_FOREIGN_KEY_VIOLATION = 'DB_FOREIGN_KEY_VIOLATION',
  DB_TRANSACTION_FAILED = 'DB_TRANSACTION_FAILED',
  DB_QUERY_INTERPRETATION_ERROR = 'DB_QUERY_INTERPRETATION_ERROR',

  // Domain / Business Logic Errors (Vouchers, Redemptions, Subscriptions)
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  REDEMPTION_CODE_EXPIRED = 'REDEMPTION_CODE_EXPIRED',
  REDEMPTION_CODE_INVALID = 'REDEMPTION_CODE_INVALID',
  REDEMPTION_ALREADY_USED = 'REDEMPTION_ALREADY_USED',
  REDEMPTION_CONCURRENT_LOCK = 'REDEMPTION_CONCURRENT_LOCK',
  INVALID_MERCHANT_PIN = 'INVALID_MERCHANT_PIN',
  OFFER_LIMIT_REACHED = 'OFFER_LIMIT_REACHED',
  GEO_FENCE_MISMATCH = 'GEO_FENCE_MISMATCH',
  IDEMPOTENCY_IN_PROGRESS = 'IDEMPOTENCY_IN_PROGRESS',
}
